### ISSUE TITLE
Add extrapolation chart for current month

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/grafana-dashboards#1]

**Comment by tswinb** [comment]
### Potential solutions:

**1)** Projection viewed as a panel showing full current month stacked with Grid and Cloud as different colours. _Issue with this solution:_ When a custom time range is set in Grafana, all panel time ranges are overwritten so that the current month bar moves out of view.
**2)** Same as **1)** but graph formatted as 'Series'. _Issue:_ cannot 'stack' bars in Series mode. This means it's hard to compare to the month so far.
**3)** Alternative display of the projection data e.g. Guage or Bar Guage. _Issue:_ Hard to compare to month so far. Possibly more confusing.

**Comment by tswinb** [comment]
Suggestion has been made that this would be most useful as a table with an extrapolation figure for each VO, rather than a combined total.

**Comment by tswinb** [comment]
Current plan is to use both option 2 and also a table with a figure for each VO. Encountering issue with option 2 that when certain filters are selected an error is received.

**Comment by tofu-rocketry** [comment]
Resolved by #38.
